"""Criação da tabela consumidor e outras tabelas

Revision ID: d573e4de6240
Revises: 
Create Date: 2024-11-29 01:14:11.160171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd573e4de6240'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_consumidor', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumidor',
    sa.Column('id_consumidor', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('email_consumidor', sa.String(length=150), nullable=False),
    sa.Column('senha_consumidor', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=250), nullable=True),
    sa.Column('requisicao_alterar_senha', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_consumidor'),
    sa.UniqueConstraint('email_consumidor')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('preco', sa.String(length=255), nullable=False),
    sa.Column('imagem', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('loja', sa.String(length=255), nullable=False),
    sa.Column('receber_alerta', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['consumidor.id_consumidor'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    op.drop_table('consumidor')
    op.drop_table('confirmacoes')
    # ### end Alembic commands ###
